name: Build My AyuGram
on: workflow_dispatch

jobs:
  build:
    runs-on: macos-15
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Patch Project
        run: |
          # Исправляем только критические нестыковки в версии и ветках
          find . -name "Package.swift" -exec sed -i '' 's/\.v26/\.v15/g' {} +
          find . -name "Package.swift" -exec sed -i '' 's/branch: "master"/branch: "main"/g' {} +

      - name: Select Xcode 16
        run: sudo xcode-select -s /Applications/Xcode_16.app

      - name: Build
        run: |
          cd iOS
          xcodebuild archive \
            -scheme AyuGram \
            -destination "generic/platform=iOS" \
            -archivePath build/AyuGram.xcarchive \
            CODE_SIGNING_ALLOWED=NO \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGN_IDENTITY=""

      - name: Export
        run: |
          mkdir -p Payload
          # Ищем приложение внутри архива и копируем его для упаковки в IPA
          find iOS/build/AyuGram.xcarchive/Products/Applications -name "*.app" -type d -exec cp -R {} Payload/ \;
          zip -r AyuGram.ipa Payload

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: AyuGram-Final-IPA
          path: AyuGram.ipa
